const About = () => {
  return (
    <main>
			<h2 class="shop-title">about</h2>
      <div className="info-box">
				<h3>welcome to shop type shop</h3>
				<p>This is a fake shop made with React. The product photographs were generated by entering the nonsensical descriptions as prompts into the AI image generator at <a href="https://www.craiyon.com/">https://www.craiyon.com/</a></p>
        <p>Even the loading screen is fake, there is no backend.</p>
        <img className="item-image" src="./images/rococo-greathelm.jpg" alt="product" />
      </div>
    </main>
  );
};

export default About; 